backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/images
public_folder: /images

collections:
  - label: Page
    name: page
    delete: false
    editor:
      preview: true
    files:
      - file: content/pages/home.md
        label: Home Page
        name: home-page
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: "" }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
