backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/images
public_folder: /images

collections:
  - label: Page
    name: page
    delete: false
    editor:
      preview: true
    files:
      - file: content/pages/home.md
        label: Home Page
        name: home-page
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: "" }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Title, name: title, widget: text },
                  { label: Body, name: body, widget: text },
                ],
            }
          - {
              label: listino,
              name: listino,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: text },
                  { label: Price, name: body, widget: text },
                ],
            }
          # Footer Section
          - {
              label: Footer,
              name: footer,
              widget: object,
              fields:
                [
                  {
                    label: Social Links. Enter 'null' for empty Links,
                    name: social,
                    widget: object,
                    fields:
                      [
                        {
                          label: Enter Facebook URL,
                          name: facebook,
                          widget: text,
                          required: false,
                        },
                        {
                          label: Enter Instagram URL,
                          name: instagram,
                          widget: text,
                          required: false,
                        },
                        {
                          label: Enter Twitter URL,
                          name: twitter,
                          widget: text,
                          required: false,
                        },
                      ],
                  },
                ],
            }
